[project]
name = "cosmic-blaster"
version = "0.1.0"
description = "Asteroids game developed in Pygame for the Boot.dev backend curriculum."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame==2.6.1",
]
